### ISSUE TITLE
Turn off/remove "Page x/X" footer.

### ISSUE THREAD

**Issue by JoshuaC3** [Edinburgh-Genome-Foundry/pdf_reports#7]
Fairly self explanatory, I'd like the option to turn off the `Page 1 of 1` footer etc, at the bottom of the PDF.

Is there currently a way of doing this? Thanks!

**Comment by Zulko** [comment]
I believe you can remove this using the (S)CSS styles:

```scss
@page {
  margin: 1cm 0 2cm 0cm;
  @bottom-center {
    content: "";
  }
}
```

PDF reports uses Weasyprint, so anything that works with Weasyprint should work with PDF reports.

Let me know if that works for you.
